//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanRequest()
        {
            this.FormFields = new HashSet<FormFields>();
        }
    
        public int Id { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public int Status { get; set; }
        public int LoanTypeId { get; set; }
        public Nullable<decimal> Score { get; set; }
        public decimal Amount { get; set; }
    
        public virtual User User { get; set; }
        public virtual LoanType LoanType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormFields> FormFields { get; set; }
    }
}
